Update code examples to use map instantiation and pass authentication in header
CartoDB/documentation pull request #415
Opened 2022-09-29 13:35 UTC by felixpalmer

In order to leverage the shared cache, non-deck.gl-based clients need to specify the `v=3.1` parameter and use only  header based authentication. Related: https://github.com/visgl/deck.gl/pull/7287/

2022-10-10 06:14 UTC, alasarr requested changes
Just realized we should change this way in mapbox gl and amazon location.

We developed these guides when we only had tilesets support and it's today only compatible when the backend returns data in MVT, so: 

- Tables will fail in all providers, but PostgreSQL
- Spatial indexes in all providers
- Tables will fail in all providers, but BigQuery

I propose to force always to use deck.gl, so we need to change these examples and do the same as we do with Google Maps.

2022-10-10 10:17 UTC, felixpalmer commented
@alasarr OK, I will rework this PR to always use deck. I think it ultimately makes it simpler, as we are then promoting one correct way of working with our backend

2022-10-13 11:11 UTC, felixpalmer commented
@alasarr I've updated the Amazon Location docs so that:

- fetchMap is used in the getting started page
- The Hello World example also uses fetchMap (same example as above)
- A new CartoLayer example is included also

I think this approach simplifies the docs and shows how users can get started with CARTO with only a few lines of code.

If you're happy with this approach, I can do the same for the Mapbox

2022-10-25 18:33 UTC, alasarr commented on app/content/amazon-location/examples/cartolayer.html
> +      deck.carto.setDefaultCredentials({accessToken: 'eyJhbGciOiJIUzI1NiJ9.eyJhIjoiYWNfbHFlM3p3Z3UiLCJqdGkiOiI1YjI0OWE2ZCJ9.Y7zB30NJFzq5fPv8W5nkoH5lPXFWQP0uywDtqUg8y8c'});
We could add the token in a variable at the top to make it easier

2022-10-25 18:34 UTC, alasarr commented on app/content/amazon-location/examples/getting-started/step-2.html
> +      const {layers} = await deck.carto.fetchMap({cartoMapId});
👍

2022-10-25 18:36 UTC, alasarr approved these changes
+1 to the idea of using fetchMap as default and adding the CartoLayer section to the doc.

Thanks a lot for the proposal, it looks great

2022-11-04 11:20 UTC, merged